refactor: clean folder

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -5,35 +5,30 @@ echo "🚀🚀 Preparing your project before committing... 👷🚧"
 
 
 echo "🧽🧽🧽 Formatting with Prettier"
-yarn format || {
-  echo "❌❌❌ Prettier Format Failed. Run yarn format.";
+bun format || {
+  echo "❌❌❌ Prettier Format Failed. Run bun format.";
   false;
 }
 
 
 echo "🧹🧹🧹 Checking ESLint"
-yarn lint || {
+bun lint || {
   echo "🤢🤢🤢 ESLint Check Failed. Make the required change above.";
   false;
 }
 
 
 echo "👷👷👷 Building your project"
-yarn build || {
+bun run build || {
   echo "🏨🏨🏨 Build Failed. Oops building failed checkout what is the problem.";
   false;
 }
 
 echo "🧪🧪🧪 Testing your project 🔬🔬🔬"
-yarn test || {
+bun run test || {
   echo "🧪🧪🧪 Test Failed. Nah man you're didnt that good.";
   false;
 }
 
-echo "⚕️ ⚕️ ⚕️  Now E2E time"
-yarn test:e2e || {
-  echo "🔬🔬🔬 E2E Test Failed. Hey this is the most important thing you know.";
-  false;
-}
 
 echo "🎉🎉🎉 You win. Committing this now. 🎉🎉🎉"
